#!/usr/bin/env python3

# Copyright 2025 Benjamin Olmstead
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Standalone driver program for the Emboss formatter."""

import argparse
import os
import sys


def main(argv):
    base_path = os.path.dirname(__file__) or "."
    sys.path.append(base_path)

    from compiler.front_end import format  # pylint:disable=import-outside-toplevel

    return format.main(argv)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
