module(
    name = "emboss",
    version = "0.0.0",
    repo_name = "com_google_emboss",
)

bazel_dep(
    name = "abseil-cpp",
    version = "20240722.0",
    repo_name = "com_google_absl",
)
bazel_dep(
    name = "googletest",
    version = "1.17.0.bcr.2",
    repo_name = "com_google_googletest",
)
bazel_dep(name = "rules_python", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.1.0")
bazel_dep(name = "rules_shell", version = "0.3.0")
bazel_dep(name = "rules_license", version = "0.0.8")
bazel_dep(name = "rules_rust", version = "0.71.3")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.79.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pip",
    python_version = "3.11",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pip")
