# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Wireshark Lua dissector code generator.

Call generate_dissector(ir) to get the text of a Wireshark Lua dissector
script implementing a `Proto` and per-`struct` dissect functions for the
given Emboss IR.
"""

import os
import re

from compiler.back_end.lua import attributes
from compiler.util import attribute_util
from compiler.util import error
from compiler.util import ir_data
from compiler.util import ir_util


_LUA_RESERVED_WORDS = frozenset(
    (
        "and",
        "break",
        "do",
        "else",
        "elseif",
        "end",
        "false",
        "for",
        "function",
        "goto",
        "if",
        "in",
        "local",
        "nil",
        "not",
        "or",
        "repeat",
        "return",
        "then",
        "true",
        "until",
        "while",
    )
)


_BANNER = "-- Generated by the Emboss Wireshark Lua dissector backend; do not edit."


def _sanitize_lua_identifier(name):
    """Returns a syntactically valid Lua identifier derived from `name`."""
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not sanitized or sanitized[0].isdigit():
        sanitized = "_" + sanitized
    if sanitized in _LUA_RESERVED_WORDS:
        sanitized = sanitized + "_"
    return sanitized


def _lua_string_escape(value):
    """Escapes a Python string for inclusion in a Lua double-quoted string."""
    out = []
    for ch in value:
        if ch == "\\" or ch == '"':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\{:03d}".format(ord(ch)))
        else:
            out.append(ch)
    return "".join(out)


def _quote(value):
    return '"' + _lua_string_escape(value) + '"'


def _module_protocol_name(module):
    """Returns the protocol name for `module`.

    If the module has a `[(wireshark) protocol: "..."]` attribute, its value
    is used; otherwise the protocol name is derived from the source file's
    basename.
    """
    attr = ir_util.get_attribute(module.attribute, attributes.Attribute.PROTOCOL)
    if attr and attr.string_constant.text:
        return _sanitize_lua_identifier(attr.string_constant.text)
    base = os.path.basename(module.source_file_name or "emboss")
    if base.endswith(".emb"):
        base = base[:-4]
    return _sanitize_lua_identifier(base) or "emboss"


def _filter_override(attribute_list):
    """Returns the `(wireshark) filter` override on a struct or field, or None."""
    attr = ir_util.get_attribute(attribute_list, attributes.Attribute.FILTER)
    if attr and attr.string_constant.text:
        return attr.string_constant.text
    return None


def _doc_text(documentation_list):
    """Joins all `--` documentation strings, ignoring `#` comments."""
    parts = [doc.text.strip() for doc in documentation_list if doc.text]
    return " ".join(part for part in parts if part)


def _local_name(canonical_name):
    """Returns the last segment of a CanonicalName's object_path."""
    return canonical_name.object_path[-1]


def _qualified_lua_name(canonical_name):
    """Returns a Lua-safe joined name for an IR object's canonical path."""
    return "_".join(
        _sanitize_lua_identifier(part) for part in canonical_name.object_path
    )


def _enum_values_var(canonical_name):
    return _qualified_lua_name(canonical_name) + "_VALUES"


def _dissector_function(canonical_name):
    return "dissect_" + _qualified_lua_name(canonical_name)


def _proto_var(protocol_name):
    return protocol_name + "_proto"


_PRIMITIVE_TYPE_NAMES = ("UInt", "Int", "Bcd", "Flag", "Float")


def _primitive_name_of(type_ir):
    """If `type_ir` is a prelude primitive, returns its name; otherwise None."""
    if not type_ir.has_field("atomic_type"):
        return None
    ref = type_ir.atomic_type.reference
    if not ref or not ref.canonical_name:
        return None
    if ref.canonical_name.module_file != "":
        return None
    path = list(ref.canonical_name.object_path)
    if len(path) != 1:
        return None
    name = path[0]
    return name if name in _PRIMITIVE_TYPE_NAMES else None


def _referenced_type_definition(type_ir, ir):
    """Returns the TypeDefinition referenced by `type_ir`, or None."""
    if not type_ir.has_field("atomic_type"):
        return None
    ref = type_ir.atomic_type.reference
    if not ref or not ref.canonical_name:
        return None
    if ref.canonical_name.module_file == "":
        return None
    return ir_util.find_object_or_none(ref, ir)


def _wireshark_int_type(primitive, size_in_bits):
    """Maps an integer-like primitive + size in bits to a Wireshark field type."""
    size_in_bytes = (size_in_bits + 7) // 8
    if primitive == "Int":
        prefix = "int"
    else:
        prefix = "uint"
    if size_in_bytes <= 1:
        return prefix + "8"
    if size_in_bytes <= 2:
        return prefix + "16"
    if size_in_bytes <= 4:
        return prefix + "32"
    return prefix + "64"


def _wireshark_float_type(size_in_bits):
    return "float" if size_in_bits == 32 else "double"


def _byte_order_of_field(field_ir):
    """Returns 'BigEndian', 'LittleEndian', or '' for the given field."""
    attr = ir_util.get_attribute(field_ir.attribute, "byte_order")
    if attr and attr.string_constant.text:
        return attr.string_constant.text
    return ""


def _add_call(byte_order):
    """Returns the appropriate `subtree:add*` call form for `byte_order`."""
    if byte_order == "LittleEndian":
        return "add_le"
    return "add"


# ---------------------------------------------------------------------------
# Expression translation
#
# Conditional fields, dynamically-located fields, and variable-length arrays
# all need to evaluate an Emboss expression at dissection time.  These helpers
# translate an Emboss IR Expression into a Lua expression string, or return
# None when the expression refers to something the back end can't (yet)
# express.  In the latter case the dependent field is skipped with a comment,
# preserving the "always emit valid Lua" guarantee.
# ---------------------------------------------------------------------------


# Emboss operators that map directly onto a Lua infix operator.  ADDITION,
# MULTIPLICATION, AND, and OR are associative and may appear with more than two
# arguments; the comparison operators are strictly binary.
_LUA_INFIX_OPERATORS = {
    ir_data.FunctionMapping.ADDITION: "+",
    ir_data.FunctionMapping.SUBTRACTION: "-",
    ir_data.FunctionMapping.MULTIPLICATION: "*",
    ir_data.FunctionMapping.EQUALITY: "==",
    ir_data.FunctionMapping.INEQUALITY: "~=",
    ir_data.FunctionMapping.AND: "and",
    ir_data.FunctionMapping.OR: "or",
    ir_data.FunctionMapping.LESS: "<",
    ir_data.FunctionMapping.LESS_OR_EQUAL: "<=",
    ir_data.FunctionMapping.GREATER: ">",
    ir_data.FunctionMapping.GREATER_OR_EQUAL: ">=",
}


def _collect_field_references(expression, out):
    """Appends every FieldReference appearing in `expression` to `out`."""
    if expression is None or expression.which_expression is None:
        return
    kind = expression.which_expression
    if kind == "field_reference":
        out.append(expression.field_reference)
    elif kind == "function":
        for arg in expression.function.args:
            _collect_field_references(arg, out)


def _translate_expression(expression, resolve_field):
    """Translates an Emboss Expression into a Lua expression string.

    Arguments:
      expression: the ir_data.Expression to translate.
      resolve_field: a callable mapping an ir_data.FieldReference to the Lua
        text holding that field's runtime value, or None if the value isn't
        available.

    Returns:
      A Lua expression string, or None if the expression can't be fully
      translated.
    """
    if expression is None or expression.which_expression is None:
        return None
    # Constant subexpressions -- including enum constants such as
    # `Kind.RESPONSE` -- fold to a literal, exactly as the C++ back end does.
    # This also covers the `constant`, `constant_reference`, and
    # `boolean_constant` expression kinds.
    value = ir_util.constant_value(expression)
    if value is not None:
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value)
    kind = expression.which_expression
    if kind == "field_reference":
        return resolve_field(expression.field_reference)
    if kind == "function":
        return _translate_function(expression.function, resolve_field)
    # A non-constant builtin_reference (e.g. `$size_in_bytes`) is not supported.
    return None


def _translate_function(function, resolve_field):
    """Translates an ir_data.Function into a Lua expression string, or None."""
    args = [_translate_expression(arg, resolve_field) for arg in function.args]
    if any(arg is None for arg in args):
        return None
    if function.function == ir_data.FunctionMapping.MAXIMUM:
        return "math.max(" + ", ".join(args) + ")"
    operator = _LUA_INFIX_OPERATORS.get(function.function)
    if operator is None or len(args) < 2:
        # CHOICE (?:), PRESENCE, the bound functions, and unary operators are
        # not supported.
        return None
    return "(" + (" " + operator + " ").join(args) + ")"


def _value_reader(primitive, size, byte_order):
    """Returns the TvbRange reader method for capturing a scalar value, or None.

    Only fixed-size integer-like fields of 1-4 bytes are capturable; Wireshark's
    `TvbRange:uint`/`:int` accessors return a plain Lua number for those widths.
    Wider or non-integer fields return None and simply aren't captured, so any
    expression referring to them is skipped rather than mistranslated.
    """
    if size is None or size < 1 or size > 4:
        return None
    little_endian = byte_order == "LittleEndian"
    if primitive == "Int":
        return "le_int" if little_endian else "int"
    if primitive in ("UInt", "Bcd", "Enum"):
        return "le_uint" if little_endian else "uint"
    return None


class _FieldEmitter:
    """Accumulates ProtoField declarations and dissector body lines."""

    def __init__(self, ir, protocol_name):
        self._ir = ir
        self._protocol_name = protocol_name
        # field_decls: list of (key, declaration) preserving definition order.
        self.field_decls = []
        # struct_bodies: list of (canonical_name, [body_lines])
        self.struct_bodies = []
        # struct_size_bytes: dict mapping canonical_name tuple -> size in bytes
        # for fixed-size byte structs; None if unknown.
        self._struct_size_bytes = {}
        self.errors = []
        # Per-struct expression-translation state, reset in visit_struct():
        #   _referenced:    hashable canonical names of fields referenced by some
        #                   sibling's condition / location / array-count.
        #   _value_locals:  hashable canonical name -> Lua local holding the
        #                   captured runtime value of that field.
        self._referenced = set()
        self._value_locals = {}

    def _emit_field_decl(self, key, declaration):
        self.field_decls.append((key, declaration))

    def _resolve_field(self, field_reference):
        """Returns the Lua local holding a referenced field's value, or None."""
        if len(field_reference.path) != 1:
            return None
        key = ir_util.hashable_form_of_reference(field_reference.path[0])
        return self._value_locals.get(key)

    def _translate(self, expression):
        """Translates `expression` to Lua, resolving sibling field references."""
        return _translate_expression(expression, self._resolve_field)

    def _compute_referenced_fields(self, struct):
        """Collects fields referenced by sibling conditions/locations/counts."""
        referenced = set()
        for field in struct.field:
            refs = []
            _collect_field_references(field.existence_condition, refs)
            # Virtual fields have no physical location, and aren't emitted.
            if field.location is not None:
                _collect_field_references(field.location.start, refs)
                _collect_field_references(field.location.size, refs)
            if (
                field.type is not None
                and field.type.has_field("array_type")
                and (field.type.array_type.which_size == "element_count")
            ):
                _collect_field_references(field.type.array_type.element_count, refs)
            for ref in refs:
                if len(ref.path) == 1:
                    referenced.add(ir_util.hashable_form_of_reference(ref.path[0]))
        return referenced

    def _maybe_capture_value(
        self, field, primitive, start_lua, size, byte_order, body_lines
    ):
        """Emits a value-capturing local for `field` if a sibling references it.

        Only called for unconditional, fixed-offset scalar fields, so the local
        is always in scope wherever a later expression uses it.
        """
        key = ir_util.hashable_form_of_reference(field.name)
        if key not in self._referenced:
            return
        reader = _value_reader(primitive, size, byte_order)
        if reader is None:
            return
        var = "val_" + _qualified_lua_name(field.name.canonical_name)
        body_lines.append(
            "local {var} = buffer(offset + {start}, {size}):{reader}()".format(
                var=var, start=start_lua, size=size, reader=reader
            )
        )
        self._value_locals[key] = var

    def _proto_filter(self, *segments):
        return ".".join((self._protocol_name,) + tuple(segments))

    def _emit_protofield(
        self,
        key,
        proto_filter,
        ws_type,
        display_name,
        base="base.DEC",
        valuestring=None,
        mask=None,
        description=None,
    ):
        """Emits one Lua `ProtoField.<ws_type>(...)` declaration.

        Wireshark's ProtoField positional signature is
        `ProtoField.<type>(abbr, name, base, valuestring, mask, desc)`.
        Trailing args may be omitted but must be padded with `nil` when an
        argument further to the right is supplied.
        """
        parts = [_quote(proto_filter), _quote(display_name)]
        need_base = bool(valuestring) or bool(mask) or bool(description)
        need_valuestring = bool(mask) or bool(description) or bool(valuestring)
        need_mask = bool(mask) or bool(description)
        need_desc = bool(description)
        if need_base:
            parts.append(base)
        if need_valuestring:
            parts.append(valuestring if valuestring else "nil")
        if need_mask:
            parts.append(mask if mask else "nil")
        if need_desc:
            parts.append(_quote(description))
        decl = "ProtoField.{}({})".format(ws_type, ", ".join(parts))
        self._emit_field_decl(key, decl)

    def visit_struct(self, type_def):
        struct = type_def.structure
        is_bits = type_def.addressable_unit == ir_data.AddressableUnit.BIT
        # Reset per-struct expression-translation state.  Value locals are only
        # emitted for fields some sibling actually refers to, so structs with no
        # conditional / dynamic fields produce exactly the same output as before.
        self._referenced = self._compute_referenced_fields(struct)
        self._value_locals = {}
        # The struct filter qualifies every contained field, so it must be
        # unique across the module.  Use the override if present; otherwise
        # the dotted canonical path of the type (e.g. `parent.child`).
        struct_filter = _filter_override(type_def.attribute) or ".".join(
            _sanitize_lua_identifier(part)
            for part in type_def.name.canonical_name.object_path
        )
        body_lines = []
        body_lines.append(
            'local subtree = tree:add({}_proto, buffer(offset), "{}")'.format(
                self._protocol_name,
                _local_name(type_def.name.canonical_name),
            )
        )

        if is_bits:
            self._emit_bits_body(type_def, struct, struct_filter, body_lines)
        else:
            self._emit_byte_struct_body(type_def, struct, struct_filter, body_lines)

        self.struct_bodies.append((type_def.name.canonical_name, body_lines))

    def _field_filter_path(self, struct_filter, field_ir):
        override = _filter_override(field_ir.attribute)
        last = override or _sanitize_lua_identifier(
            _local_name(field_ir.name.canonical_name)
        )
        return struct_filter + "." + last

    def _emit_byte_struct_body(self, type_def, struct, struct_filter, body_lines):
        protocol_filter_base = struct_filter
        for index in struct.fields_in_dependency_order or list(
            range(len(struct.field))
        ):
            field = struct.field[index]
            self._emit_byte_field(
                type_def, struct, field, protocol_filter_base, body_lines
            )

    def _emit_byte_field(self, type_def, struct, field, struct_filter, body_lines):
        if ir_util.field_is_virtual(field):
            # Virtual fields (including the synthetic `$size_in_bytes`,
            # `$max_size_in_bytes`, and `$min_size_in_bytes`) have no on-wire
            # representation, so the dissector simply doesn't emit anything
            # for them.
            return

        field_name = _local_name(field.name.canonical_name)

        # Presence condition.  Unconditional fields get no wrapper; a
        # conditional field whose condition can't be translated is skipped.
        conditional = not _is_unconditional(field)
        condition_lua = None
        if conditional:
            condition_lua = self._translate(field.existence_condition)
            if condition_lua is None:
                body_lines.append(
                    "-- skipped conditional field {} (unsupported condition)".format(
                        field_name
                    )
                )
                return

        # Field location.  A constant start renders to an integer literal, so
        # fixed-offset fields produce byte-identical output to the prior
        # constant-only implementation.
        start_lua = self._translate(field.location.start)
        if start_lua is None:
            body_lines.append("-- skipped dynamic-location field {}".format(field_name))
            return
        size = ir_util.constant_value(field.location.size)

        proto_filter = self._proto_filter(self._field_filter_path(struct_filter, field))
        key = _qualified_lua_name(type_def.name.canonical_name) + "." + field_name
        doc = _doc_text(field.documentation)
        byte_order = _byte_order_of_field(field)

        type_ir = field.type
        primitive = _primitive_name_of(type_ir)
        referenced_type = (
            None if primitive else _referenced_type_definition(type_ir, self._ir)
        )
        is_enum = referenced_type is not None and referenced_type.has_field(
            "enumeration"
        )

        # Capture this field's value for any sibling expression that refers to
        # it.  Only unconditional, fixed-size scalar fields are eligible, so the
        # local is always emitted at function-body scope (never inside the `if`
        # wrapper below) and is therefore in scope wherever it is used.
        if not conditional:
            capture_primitive = primitive or ("Enum" if is_enum else None)
            if capture_primitive is not None:
                self._maybe_capture_value(
                    field, capture_primitive, start_lua, size, byte_order, body_lines
                )

        field_lines = []
        if type_ir.has_field("array_type"):
            self._emit_byte_array_field(
                type_def,
                field,
                type_ir,
                start_lua,
                size,
                proto_filter,
                key,
                doc,
                byte_order,
                field_lines,
            )
        elif primitive:
            if size is None:
                field_lines.append(
                    "-- skipped dynamic-size field {}".format(field_name)
                )
            else:
                self._emit_primitive_field(
                    primitive,
                    field_name,
                    proto_filter,
                    key,
                    start_lua,
                    size,
                    doc,
                    byte_order,
                    field_lines,
                )
        elif referenced_type is None:
            field_lines.append(
                "-- skipped field with unsupported type: {}".format(field_name)
            )
        elif is_enum:
            if size is None:
                field_lines.append(
                    "-- skipped dynamic-size field {}".format(field_name)
                )
            else:
                self._emit_enum_field(
                    referenced_type,
                    field_name,
                    proto_filter,
                    key,
                    start_lua,
                    size,
                    doc,
                    byte_order,
                    field_lines,
                )
        elif referenced_type.has_field("structure"):
            self._emit_substruct_field(
                referenced_type,
                field_name,
                start_lua,
                size,
                doc,
                field_lines,
            )
        else:
            field_lines.append(
                "-- skipped field with unsupported type: {}".format(field_name)
            )

        if conditional:
            body_lines.append("if {} then".format(condition_lua))
            body_lines.extend("  " + line for line in field_lines)
            body_lines.append("end")
        else:
            body_lines.extend(field_lines)

    def _emit_primitive_field(
        self,
        primitive,
        field_name,
        proto_filter,
        key,
        start,
        size,
        doc,
        byte_order,
        body_lines,
    ):
        size_in_bits = size * 8
        if primitive == "Flag":
            ws_type = "bool"
        elif primitive == "Float":
            ws_type = _wireshark_float_type(size_in_bits)
        else:
            ws_type = _wireshark_int_type(primitive, size_in_bits)
        self._emit_protofield(
            key,
            proto_filter,
            ws_type,
            field_name,
            description=doc or None,
        )
        body_lines.append(
            "subtree:{call}(f[{key}], buffer(offset + {start}, {size}))".format(
                call=_add_call(byte_order),
                key=_quote(key),
                start=start,
                size=size,
            )
        )

    def _emit_enum_field(
        self,
        enum_type_def,
        field_name,
        proto_filter,
        key,
        start,
        size,
        doc,
        byte_order,
        body_lines,
    ):
        ws_type = _wireshark_int_type("UInt", size * 8)
        valuestring = _enum_values_var(enum_type_def.name.canonical_name)
        self._emit_protofield(
            key,
            proto_filter,
            ws_type,
            field_name,
            valuestring=valuestring,
            description=doc or None,
        )
        body_lines.append(
            "subtree:{call}(f[{key}], buffer(offset + {start}, {size}))".format(
                call=_add_call(byte_order),
                key=_quote(key),
                start=start,
                size=size,
            )
        )

    def _emit_substruct_field(
        self,
        sub_type_def,
        field_name,
        start,
        size,
        doc,
        body_lines,
    ):
        body_lines.append("-- nested field {}".format(field_name))
        if doc:
            body_lines.append("-- {}".format(doc))
        body_lines.append(
            "{fn}(buffer, pinfo, subtree, offset + {start})".format(
                fn=_dissector_function(sub_type_def.name.canonical_name),
                start=start,
            )
        )

    def _emit_byte_array_field(
        self,
        type_def,
        field,
        type_ir,
        start,
        size,
        proto_filter,
        key,
        doc,
        byte_order,
        body_lines,
    ):
        # Explicit-element-count arrays only (`[n]`, constant or a reference to
        # a sibling length field); auto-sized (`[]`) arrays are skipped.  The
        # element size must be a whole number of bytes.
        array_type = type_ir.array_type
        field_name = _local_name(field.name.canonical_name)
        if array_type.which_size != "element_count":
            body_lines.append("-- skipped auto-sized array field {}".format(field_name))
            return
        element_count = ir_util.constant_value(array_type.element_count)
        if element_count is not None:
            if element_count <= 0:
                body_lines.append("-- skipped empty array field {}".format(field_name))
                return
            count_lua = str(element_count)
        else:
            # A variable element count, e.g. `UInt:8[length]`.  Translatable
            # only if every field it references was captured as a value local.
            count_lua = self._translate(array_type.element_count)
            if count_lua is None:
                body_lines.append(
                    "-- skipped variable-length array field {} "
                    "(unsupported length)".format(field_name)
                )
                return

        element_size_bits = ir_util.fixed_size_of_type_in_bits(
            array_type.base_type, self._ir
        )
        if element_size_bits is None or element_size_bits % 8 != 0:
            body_lines.append(
                "-- skipped array with non-byte element size: {}".format(field_name)
            )
            return
        element_size = element_size_bits // 8
        body_lines.append(
            "-- array field {} ({} elements)".format(field_name, count_lua)
        )

        base_type = array_type.base_type
        primitive = _primitive_name_of(base_type)
        if primitive:
            if primitive == "Flag":
                ws_type = "bool"
            elif primitive == "Float":
                ws_type = _wireshark_float_type(element_size_bits)
            else:
                ws_type = _wireshark_int_type(primitive, element_size_bits)
            self._emit_protofield(
                key,
                proto_filter,
                ws_type,
                field_name,
                description=doc or None,
            )
            body_lines.append("for i = 0, {n} - 1 do".format(n=count_lua))
            body_lines.append(
                "  subtree:{call}(f[{key}], buffer(offset + {start} + i * "
                "{esize}, {esize}))".format(
                    call=_add_call(byte_order),
                    key=_quote(key),
                    start=start,
                    esize=element_size,
                )
            )
            body_lines.append("end")
            return

        referenced = _referenced_type_definition(base_type, self._ir)
        if referenced and referenced.has_field("enumeration"):
            ws_type = _wireshark_int_type("UInt", element_size_bits)
            valuestring = _enum_values_var(referenced.name.canonical_name)
            self._emit_protofield(
                key,
                proto_filter,
                ws_type,
                field_name,
                valuestring=valuestring,
                description=doc or None,
            )
            body_lines.append("for i = 0, {n} - 1 do".format(n=count_lua))
            body_lines.append(
                "  subtree:{call}(f[{key}], buffer(offset + {start} + i * "
                "{esize}, {esize}))".format(
                    call=_add_call(byte_order),
                    key=_quote(key),
                    start=start,
                    esize=element_size,
                )
            )
            body_lines.append("end")
            return

        if referenced and referenced.has_field("structure"):
            body_lines.append("for i = 0, {n} - 1 do".format(n=count_lua))
            body_lines.append(
                "  {fn}(buffer, pinfo, subtree, offset + {start} + i * "
                "{esize})".format(
                    fn=_dissector_function(referenced.name.canonical_name),
                    start=start,
                    esize=element_size,
                )
            )
            body_lines.append("end")
            return

        body_lines.append("-- skipped array of unsupported type: {}".format(field_name))

    def _emit_bits_body(self, type_def, struct, struct_filter, body_lines):
        # `bits` blocks are read as a single big-endian unsigned integer of
        # the total bit width (rounded up to a byte boundary), with each
        # sub-field exposed as a masked ProtoField on that same buffer slice.
        total_bits = 0
        for field in struct.field:
            if ir_util.field_is_virtual(field) or not _is_unconditional(field):
                continue
            start = ir_util.constant_value(field.location.start)
            size = ir_util.constant_value(field.location.size)
            if start is None or size is None:
                continue
            total_bits = max(total_bits, start + size)
        if total_bits == 0:
            return
        total_bytes = (total_bits + 7) // 8
        ws_container_type = _wireshark_int_type("UInt", total_bits)

        for field in struct.field:
            if ir_util.field_is_virtual(field):
                continue
            if not _is_unconditional(field):
                body_lines.append(
                    "-- skipped conditional field {}".format(
                        _local_name(field.name.canonical_name)
                    )
                )
                continue
            start = ir_util.constant_value(field.location.start)
            size = ir_util.constant_value(field.location.size)
            if start is None or size is None:
                body_lines.append(
                    "-- skipped dynamic-location field {}".format(
                        _local_name(field.name.canonical_name)
                    )
                )
                continue
            field_name = _local_name(field.name.canonical_name)
            key = _qualified_lua_name(type_def.name.canonical_name) + "." + field_name
            proto_filter = self._proto_filter(
                self._field_filter_path(struct_filter, field)
            )
            mask_bits = ((1 << size) - 1) << (total_bits - start - size)
            mask = "0x{:0{w}X}".format(mask_bits, w=total_bytes * 2)
            doc = _doc_text(field.documentation)

            primitive = _primitive_name_of(field.type)
            referenced = _referenced_type_definition(field.type, self._ir)
            if primitive == "Flag":
                ws_type = "bool"
                # `ProtoField.bool` uses `parent_bitlen` instead of `base`.
                # Emit a raw declaration so we can pass total_bits as the
                # 3rd positional argument.
                parts = [_quote(proto_filter), _quote(field_name), str(total_bits)]
                if doc:
                    parts += ["nil", mask, _quote(doc)]
                else:
                    parts += ["nil", mask]
                decl = "ProtoField.bool({})".format(", ".join(parts))
                self._emit_field_decl(key, decl)
            elif referenced and referenced.has_field("enumeration"):
                ws_type = ws_container_type
                valuestring = _enum_values_var(referenced.name.canonical_name)
                self._emit_protofield(
                    key,
                    proto_filter,
                    ws_type,
                    field_name,
                    valuestring=valuestring,
                    mask=mask,
                    description=doc or None,
                )
            elif primitive in ("UInt", "Bcd"):
                ws_type = ws_container_type
                self._emit_protofield(
                    key,
                    proto_filter,
                    ws_type,
                    field_name,
                    mask=mask,
                    description=doc or None,
                )
            elif primitive == "Int":
                # Signed integers in masked bit fields are uncommon; expose
                # as the corresponding signed Wireshark type but still
                # against the container's byte width.
                ws_type = _wireshark_int_type("Int", total_bits)
                self._emit_protofield(
                    key,
                    proto_filter,
                    ws_type,
                    field_name,
                    mask=mask,
                    description=doc or None,
                )
            else:
                body_lines.append(
                    "-- skipped bits field with unsupported type: {}".format(field_name)
                )
                continue

            body_lines.append(
                "subtree:add(f[{key}], buffer(offset, {n}))".format(
                    key=_quote(key), n=total_bytes
                )
            )


def _is_unconditional(field):
    """Returns True iff the field is unconditionally present."""
    cond = field.existence_condition
    if cond is None:
        return True
    if cond.has_field("boolean_constant"):
        return cond.boolean_constant.value is True
    if cond.type and cond.type.boolean and cond.type.boolean.has_field("value"):
        return cond.type.boolean.value is True
    return False


def _generate_enum_values_table(type_def):
    """Generates a Lua table mapping enum integer values to value names."""
    enum = type_def.enumeration
    lines = ["local {} = {{".format(_enum_values_var(type_def.name.canonical_name))]
    for value in enum.value:
        if not value.name or not value.value:
            continue
        numeric = ir_util.constant_value(value.value)
        if numeric is None:
            continue
        lines.append(
            "  [{}] = {},".format(
                numeric, _quote(_local_name(value.name.canonical_name))
            )
        )
    lines.append("}")
    return "\n".join(lines)


def _propagate_defaults_and_verify_attributes(ir):
    """Validates `(wireshark)` back-end attributes throughout the IR."""
    return attribute_util.check_attributes_in_ir(
        ir,
        back_end=attributes.BACK_END,
        types=attributes.TYPES,
        module_attributes=attributes.Scope.MODULE,
        struct_attributes=attributes.Scope.STRUCT,
        bits_attributes=attributes.Scope.BITS,
        structure_physical_field_attributes=attributes.Scope.STRUCT_PHYSICAL_FIELD,
    )


def _module_has_dissectable_root(module):
    for type_def in module.type:
        if type_def.has_field("structure"):
            return True
    return False


def _is_byte_struct(type_def):
    return (
        type_def.has_field("structure")
        and type_def.addressable_unit == ir_data.AddressableUnit.BYTE
    )


def _all_types(module):
    """Yields every TypeDefinition in `module`, recursing into subtypes.

    Order is preorder (parent before children) and otherwise preserves the
    order types appear in the source file.
    """

    def walk(type_def):
        yield type_def
        for sub in type_def.subtype:
            yield from walk(sub)

    for top in module.type:
        yield from walk(top)


def generate_dissector(ir):
    """Generates a Wireshark Lua dissector from `ir`.

    Returns:
      (text, errors) — `text` is the Lua source on success, and `errors` is
      a list of error lists in the same shape as the C++ backend uses.
    """
    errors = _propagate_defaults_and_verify_attributes(ir)
    if errors:
        return "", errors

    module = ir.module[0]
    protocol_name = _module_protocol_name(module)
    proto_var = _proto_var(protocol_name)

    lines = [_BANNER]
    if module.source_file_name:
        lines.append("-- Source: " + module.source_file_name)
    lines.append("")

    module_doc = _doc_text(module.documentation)
    if module_doc:
        lines.append("-- " + module_doc)
        lines.append("")

    lines.append(
        "local {proto} = Proto({name}, {desc})".format(
            proto=proto_var,
            name=_quote(protocol_name),
            desc=_quote(protocol_name + " (Emboss)"),
        )
    )
    lines.append("")

    # Enum value-strings tables for every enum in the module (including
    # enums nested inside structs / bits).
    enum_blocks = []
    for type_def in _all_types(module):
        if type_def.has_field("enumeration"):
            enum_blocks.append(_generate_enum_values_table(type_def))
    if enum_blocks:
        lines.extend(enum_blocks)
        lines.append("")

    # Build struct bodies / field declarations for every struct / bits
    # (including those nested in other structs).
    emitter = _FieldEmitter(ir, protocol_name)
    for type_def in _all_types(module):
        if type_def.has_field("structure"):
            emitter.visit_struct(type_def)

    if emitter.field_decls:
        lines.append("local f = {}")
        for key, decl in emitter.field_decls:
            lines.append("f[{}] = {}".format(_quote(key), decl))
        lines.append("")
        lines.append("{proto}.fields = {{".format(proto=proto_var))
        for key, _ in emitter.field_decls:
            lines.append("  f[{}],".format(_quote(key)))
        lines.append("}")
        lines.append("")

    # Forward-declare all dissect functions as locals first, so dissectors
    # may reference each other regardless of definition order.
    if emitter.struct_bodies:
        lines.append(
            "local "
            + ", ".join(_dissector_function(cn) for cn, _ in emitter.struct_bodies)
        )
        lines.append("")

    # Per-struct dissector functions.
    for canonical_name, body_lines in emitter.struct_bodies:
        lines.append(
            "function {}(buffer, pinfo, tree, offset)".format(
                _dissector_function(canonical_name)
            )
        )
        for body_line in body_lines:
            lines.append("  " + body_line)
        lines.append("end")
        lines.append("")

    # Top-level dissector.  Pick the root struct from the (wireshark) root
    # module attribute if set; otherwise default to the first struct
    # declared at module scope.
    root_attr = ir_util.get_attribute(module.attribute, attributes.Attribute.ROOT)
    root = None
    if root_attr:
        requested = root_attr.string_constant.text
        for type_def in module.type:
            if (
                type_def.has_field("structure")
                and _local_name(type_def.name.canonical_name) == requested
            ):
                root = type_def
                break
        if root is None:
            return "", [
                [
                    error.error(
                        module.source_file_name,
                        root_attr.source_location,
                        "(wireshark) root references unknown struct {!r}".format(
                            requested
                        ),
                    )
                ]
            ]
    else:
        for type_def in module.type:
            if type_def.has_field("structure"):
                root = type_def
                break

    lines.append(
        "function {proto}.dissector(buffer, pinfo, tree)".format(proto=proto_var)
    )
    lines.append("  pinfo.cols.protocol = {}".format(_quote(protocol_name.upper())))
    if root is not None:
        lines.append(
            "  {}(buffer, pinfo, tree, 0)".format(
                _dissector_function(root.name.canonical_name)
            )
        )
    else:
        lines.append("  -- No top-level struct found; nothing to dissect.")
    lines.append("end")
    lines.append("")

    register_attr = ir_util.get_attribute(
        module.attribute, attributes.Attribute.REGISTER_ON
    )
    if register_attr:
        registrations, parse_error = _parse_register_on(
            register_attr.string_constant.text
        )
        if parse_error is not None:
            return "", [
                [
                    error.error(
                        module.source_file_name,
                        register_attr.source_location,
                        parse_error,
                    )
                ]
            ]
        for table_name, pattern in registrations:
            lines.append(
                "DissectorTable.get({table}):add({pattern}, {proto})".format(
                    table=_quote(table_name),
                    pattern=pattern,
                    proto=proto_var,
                )
            )
    else:
        lines.append(
            "-- To register this dissector automatically, add a"
            " `[(wireshark) register_on: ...]`"
        )
        lines.append(
            '-- module attribute (e.g. `register_on: "udp.port == 12345"`),'
            " or uncomment:"
        )
        lines.append('-- DissectorTable.get("udp.port"):add(0, {})'.format(proto_var))
    lines.append("")

    return "\n".join(lines), []


_REGISTER_ON_TERM_RE = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_.]*)\s*==\s*(0[xX][0-9A-Fa-f]+|\d+)\s*$"
)
_REGISTER_ON_SPLIT_RE = re.compile(r"\s+or\s+|\s*\|\|\s*", re.IGNORECASE)


def _parse_register_on(value):
    """Parses `(wireshark) register_on` into `[(table_name, pattern_int)]`.

    Returns:
      (registrations, error_message). On success, error_message is None.
      On failure, registrations is an empty list and error_message is a
      string suitable for an error.error(...) call.
    """
    if not value.strip():
        return [], (
            "(wireshark) register_on must contain at least one"
            ' "<table> == <pattern>" expression.'
        )
    terms = _REGISTER_ON_SPLIT_RE.split(value)
    out = []
    for term in terms:
        match = _REGISTER_ON_TERM_RE.match(term)
        if not match:
            return [], (
                "Invalid (wireshark) register_on expression: {!r}. Expected"
                ' one or more "<table> == <integer>" terms separated by'
                ' "or" or "||".'.format(term.strip())
            )
        table_name = match.group(1)
        pattern_text = match.group(2)
        pattern = int(pattern_text, 0)
        out.append((table_name, pattern))
    return out, None
