-- Generated by the Emboss Wireshark Lua dissector backend; do not edit.
-- Source: testdata/enum.emb

local enum_proto = Proto("enum", "enum (Emboss)")

local Kind_VALUES = {
  [0] = "WIDGET",
  [1] = "SPROCKET",
  [2] = "GEEGAW",
  [3] = "COMPUTED",
  [2000] = "LARGE_VALUE",
  [2000] = "DUPLICATE_LARGE_VALUE",
  [4294967295] = "MAX32BIT",
  [18446744073709551615] = "MAX64BIT",
}
local Signed_VALUES = {
  [-9223372036854775808] = "MIN64BIT",
  [9223372036854775807] = "MAX64BIT",
}
local OnlyShortValues_VALUES = {
  [0] = "ZERO",
  [1] = "ONE",
}
local OnlyShortSignedValues_VALUES = {
  [0] = "ZERO",
  [-1] = "NEGATIVE_ONE",
}
local ExplicitlySigned_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySized64_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySized32_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySized16_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySized8_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySized12_VALUES = {
  [0] = "ZERO",
}
local ExplicitlySizedAndSigned_VALUES = {
  [0] = "ZERO",
}
local StructContainingEnum_Status_VALUES = {
  [0] = "OK",
  [1] = "FAILURE",
}

local f = {}
f["ManifestEntry.kind"] = ProtoField.uint8("enum.ManifestEntry.kind", "kind", base.DEC, Kind_VALUES)
f["ManifestEntry.count"] = ProtoField.uint32("enum.ManifestEntry.count", "count")
f["ManifestEntry.wide_kind"] = ProtoField.uint32("enum.ManifestEntry.wide_kind", "wide_kind", base.DEC, Kind_VALUES)
f["ManifestEntry_EmbossReservedAnonymousField1.wide_kind_in_bits"] = ProtoField.uint64("enum.ManifestEntry.EmbossReservedAnonymousField1.wide_kind_in_bits", "wide_kind_in_bits", base.DEC, Kind_VALUES, 0x00FFFFFFFF)
f["StructContainingEnum.bar"] = ProtoField.uint8("enum.StructContainingEnum.bar", "bar")

enum_proto.fields = {
  f["ManifestEntry.kind"],
  f["ManifestEntry.count"],
  f["ManifestEntry.wide_kind"],
  f["ManifestEntry_EmbossReservedAnonymousField1.wide_kind_in_bits"],
  f["StructContainingEnum.bar"],
}

local dissect_Constants, dissect_ManifestEntry, dissect_ManifestEntry_EmbossReservedAnonymousField1, dissect_StructContainingEnum

function dissect_Constants(buffer, pinfo, tree, offset)
  local subtree = tree:add(enum_proto, buffer(offset), "Constants")
end

function dissect_ManifestEntry(buffer, pinfo, tree, offset)
  local subtree = tree:add(enum_proto, buffer(offset), "ManifestEntry")
  subtree:add_le(f["ManifestEntry.kind"], buffer(offset + 0, 1))
  subtree:add_le(f["ManifestEntry.count"], buffer(offset + 1, 4))
  subtree:add_le(f["ManifestEntry.wide_kind"], buffer(offset + 5, 4))
  -- nested field emboss_reserved_anonymous_field_1
  dissect_ManifestEntry_EmbossReservedAnonymousField1(buffer, pinfo, subtree, offset + 9)
end

function dissect_ManifestEntry_EmbossReservedAnonymousField1(buffer, pinfo, tree, offset)
  local subtree = tree:add(enum_proto, buffer(offset), "EmbossReservedAnonymousField1")
  subtree:add(f["ManifestEntry_EmbossReservedAnonymousField1.wide_kind_in_bits"], buffer(offset, 5))
end

function dissect_StructContainingEnum(buffer, pinfo, tree, offset)
  local subtree = tree:add(enum_proto, buffer(offset), "StructContainingEnum")
  subtree:add_le(f["StructContainingEnum.bar"], buffer(offset + 0, 1))
end

function enum_proto.dissector(buffer, pinfo, tree)
  pinfo.cols.protocol = "ENUM"
  dissect_Constants(buffer, pinfo, tree, 0)
end

-- To register this dissector automatically, add a `[(wireshark) register_on: ...]`
-- module attribute (e.g. `register_on: "udp.port == 12345"`), or uncomment:
-- DissectorTable.get("udp.port"):add(0, enum_proto)
