-- Generated by the Emboss Wireshark Lua dissector backend; do not edit.
-- Source: testdata/wireshark.emb

-- Smoke-test fixture for the Wireshark Lua dissector backend.

local myproto_proto = Proto("myproto", "myproto (Emboss)")

local Kind_VALUES = {
  [0] = "REQUEST",
  [1] = "RESPONSE",
  [2] = "ERROR",
}

local f = {}
f["Header.kind"] = ProtoField.uint8("myproto.hdr.kind", "kind", base.DEC, Kind_VALUES, nil, "Message kind.")
f["Header.seq_num"] = ProtoField.uint32("myproto.hdr.seq_num", "seq_num", base.DEC, nil, nil, "Sequence number used for matching requests with responses.")
f["Packet.payload_len"] = ProtoField.uint32("myproto.Packet.payload_len", "payload_len", base.DEC, nil, nil, "Number of bytes of payload following.")
f["Packet.checksum"] = ProtoField.uint32("myproto.Packet.checksum", "checksum")

myproto_proto.fields = {
  f["Header.kind"],
  f["Header.seq_num"],
  f["Packet.payload_len"],
  f["Packet.checksum"],
}

local dissect_Header, dissect_Packet

function dissect_Header(buffer, pinfo, tree, offset)
  local subtree = tree:add(myproto_proto, buffer(offset), "Header")
  subtree:add(f["Header.kind"], buffer(offset + 0, 1))
  subtree:add(f["Header.seq_num"], buffer(offset + 1, 4))
end

function dissect_Packet(buffer, pinfo, tree, offset)
  local subtree = tree:add(myproto_proto, buffer(offset), "Packet")
  -- nested field header
  dissect_Header(buffer, pinfo, subtree, offset + 0)
  subtree:add(f["Packet.payload_len"], buffer(offset + 5, 4))
  subtree:add(f["Packet.checksum"], buffer(offset + 9, 4))
end

function myproto_proto.dissector(buffer, pinfo, tree)
  pinfo.cols.protocol = "MYPROTO"
  dissect_Packet(buffer, pinfo, tree, 0)
end

DissectorTable.get("udp.port"):add(12345, myproto_proto)
DissectorTable.get("tcp.port"):add(12345, myproto_proto)
